add_library(coco_options INTERFACE)
target_compile_features(coco_options INTERFACE cxx_std_17)
set(CMAKE_CXX_EXTENSIONS OFF)
if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
  target_compile_options(coco_options INTERFACE -Wall -Wextra -Wpedantic)
endif()
